/* ============================================================
   GLOBE.JS — Revolving Dot-Matrix Globe (About section)
   Amour Affairs · Premium Wedding Photography

   A luminous gold sphere: continents rendered as a field of dots
   sampled from an equirectangular land mask, a faint wireframe
   that holds the silhouette, elliptical orbit rings that pass
   both behind and in front, and a few slow travelling glints.

   Canvas 2D on purpose — the page ships no 3D library, and this
   keeps the JS delta at zero. Depth is resolved with a painter's
   pass order (rings behind → sphere → rings in front) plus a
   per-point luminance/size falloff, which is all the occlusion
   this composition needs.

   Land mask: /land-mask.png, generated by scripts/build-land-mask.mjs
   from Natural Earth 110m data (public domain).

   Degradation, in order:
     mask loads      → dotted continents + wireframe + rings
     mask fails      → wireframe + rings only (never an empty box)
     no 2D context   → canvas stays hidden, section reads fine
   Reduced motion / low-power / phones render a single static frame.
   ============================================================ */

/* Palette — mirrors the tokens in variables.css. No new colours. */
const GOLD_DEEP  = [158, 122, 78];   // --color-accent       #9E7A4E
const GOLD_LIGHT = [201, 169, 124];  // --color-accent-light #C9A97C
// On a cream page a glint cannot read by being "brighter" — white is barely
// 1% above the background. What reads is saturation: a warm gold flare with a
// tight near-white centre. #C19A57 is the site's button gold (--color-btn).
const GLINT_HOT   = 'rgba(255, 253, 248,';
const GLINT_FLARE = 'rgba(193, 154, 87,';
const GOLD_HALO   = 'rgba(214, 184, 144,';

const TAU = Math.PI * 2;

/* Tilted spin axis + viewing angle (radians) */
const AXIS_TILT = 0.34;   // ~19° off vertical
const VIEW_TILT = -0.16;  // looking very slightly down on it

/* One revolution ≈ 58s at 60fps */
const SPIN_SPEED = TAU / (58 * 60);

/* Light direction — upper right front, matching the reference */
const LIGHT = (() => {
  const v = [0.45, 0.5, 0.74];
  const m = Math.hypot(...v);
  return [v[0] / m, v[1] / m, v[2] / m];
})();

/* How far each ring's azimuth swings either side of its base angle */
const RING_SWAY = 0.45;

/* Orbit rings: radius scale, ellipse squash, inclination, azimuth, speed */
const RINGS = [
  { r: 1.34, squash: 0.58, inc: -0.28, azi: 0.55, speed:  0.00042, w: 1.6, a: 0.95 },
  { r: 1.18, squash: 0.44, inc:  0.62, azi: -0.3, speed: -0.00031, w: 1.2, a: 0.80 },
  { r: 1.55, squash: 0.40, inc:  0.18, azi: 0.85, speed:  0.00024, w: 1.4, a: 0.70 },
  { r: 1.10, squash: 0.66, inc: -0.75, azi: 0.15, speed: -0.00018, w: 1.0, a: 0.62 },
];

/* Glints travelling the rings: ring index, start offset, speed */
const GLINTS = [
  { ring: 0, t: 0.10, speed: 0.00085 },
  { ring: 2, t: 0.55, speed: 0.00061 },
  { ring: 1, t: 0.80, speed: -0.00048 },
];

const prefersReducedMotion = () =>
  window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* Phones, low-core devices and reduced-motion users get one static frame:
   full composition, zero ongoing cost. Mobile is a large share of this
   site's traffic and must not regress. */
function isStaticMode() {
  if (prefersReducedMotion()) return true;
  if (window.matchMedia('(max-width: 767px)').matches) return true;
  if (window.matchMedia('(pointer: coarse)').matches) return true;
  const cores = navigator.hardwareConcurrency;
  return typeof cores === 'number' && cores > 0 && cores <= 4;
}

/* ── Fibonacci sphere: even coverage, no polar bunching ── */
function fibonacciSphere(count) {
  const pts = new Float32Array(count * 3);
  const golden = Math.PI * (3 - Math.sqrt(5));
  for (let i = 0; i < count; i++) {
    const y = 1 - (i / (count - 1)) * 2;
    const r = Math.sqrt(Math.max(0, 1 - y * y));
    const th = golden * i;
    pts[i * 3]     = Math.cos(th) * r;
    pts[i * 3 + 1] = y;
    pts[i * 3 + 2] = Math.sin(th) * r;
  }
  return pts;
}

/* ── Land mask → keep only the points that fall on land ── */
function loadLandPoints(candidates) {
  return new Promise((resolve) => {
    const img = new Image();
    img.decoding = 'async';
    img.onload = () => {
      try {
        const mw = img.naturalWidth;
        const mh = img.naturalHeight;
        const off = document.createElement('canvas');
        off.width = mw;
        off.height = mh;
        const octx = off.getContext('2d', { willReadFrequently: true });
        octx.drawImage(img, 0, 0);
        const data = octx.getImageData(0, 0, mw, mh).data;

        const src = fibonacciSphere(candidates);
        const keep = [];
        for (let i = 0; i < candidates; i++) {
          const x = src[i * 3], y = src[i * 3 + 1], z = src[i * 3 + 2];
          const u = (Math.atan2(z, x) + Math.PI) / TAU;
          const v = 0.5 - Math.asin(y) / Math.PI;
          const px = Math.min(mw - 1, Math.max(0, (u * mw) | 0));
          const py = Math.min(mh - 1, Math.max(0, (v * mh) | 0));
          if (data[(py * mw + px) * 4] > 127) keep.push(x, y, z);
        }
        resolve(new Float32Array(keep));
      } catch {
        resolve(null); // canvas tainted or read blocked — wireframe only
      }
    };
    img.onerror = () => resolve(null);
    img.src = '/land-mask.png';
  });
}

export function initGlobe() {
  const canvas = document.getElementById('aboutGlobe');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const staticMode = isStaticMode();
  // ~1/3 of candidates survive the land mask. The static frame can afford a
  // denser field since it is drawn exactly once.
  const CANDIDATES = staticMode ? 26000 : 21000;

  let W = 0, H = 0, R = 0, cx = 0, cy = 0, dpr = 1;
  let points = null;          // Float32Array of land unit vectors
  let sizeJitter = null;      // per-point size/opacity variance
  let spin = 0;
  let ringPhase = 0;
  let raf = null;
  let visible = false;
  let ready = false;

  /* Pointer parallax, heavily damped */
  const pointer = { x: 0, y: 0, tx: 0, ty: 0 };

  /* ── Sizing ── */
  function resize() {
    const rect = canvas.getBoundingClientRect();
    W = rect.width;
    H = rect.height;
    if (!W || !H) return false;

    dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width  = Math.round(W * dpr);
    canvas.height = Math.round(H * dpr);
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    cx = W / 2;
    cy = H / 2;
    // Leaves room for the widest orbit ring (1.55R) to stay inside the box
    R = Math.min(W, H) * 0.305;
    glowLayer = null; // rebuilt lazily at the new size
    return true;
  }

  /* ── Rotate a unit vector into view space ── */
  function rotate(x, y, z, sinS, cosS) {
    // spin about the globe's own axis
    let x1 =  x * cosS + z * sinS;
    let z1 = -x * sinS + z * cosS;
    let y1 =  y;

    // lean the axis over (about Z)
    const ca = Math.cos(AXIS_TILT + pointer.x * 0.06);
    const sa = Math.sin(AXIS_TILT + pointer.x * 0.06);
    const x2 = x1 * ca - y1 * sa;
    const y2 = x1 * sa + y1 * ca;

    // viewing angle (about X)
    const cv = Math.cos(VIEW_TILT + pointer.y * 0.08);
    const sv = Math.sin(VIEW_TILT + pointer.y * 0.08);
    const y3 = y2 * cv - z1 * sv;
    const z3 = y2 * sv + z1 * cv;

    return [x2, y3, z3];
  }

  /* ── Soft radial glow behind the sphere ──
     Two full-canvas gradient fills a frame dominated the frame cost and
     neither depends on the rotation, so they are baked once per resize
     and blitted. */
  let glowLayer = null;

  function buildGlow() {
    glowLayer = document.createElement('canvas');
    glowLayer.width = Math.round(W * dpr);
    glowLayer.height = Math.round(H * dpr);
    const g2 = glowLayer.getContext('2d');
    g2.setTransform(dpr, 0, 0, dpr, 0, 0);

    // Broad bloom
    const g = g2.createRadialGradient(cx, cy, R * 0.2, cx, cy, R * 1.7);
    g.addColorStop(0, `rgba(${GOLD_LIGHT.join(',')},0.26)`);
    g.addColorStop(0.45, `rgba(${GOLD_LIGHT.join(',')},0.11)`);
    g.addColorStop(1, `rgba(${GOLD_LIGHT.join(',')},0)`);
    g2.fillStyle = g;
    g2.beginPath();
    g2.arc(cx, cy, R * 1.7, 0, TAU);
    g2.fill();

    // Offset highlight on the lit side — gives the sphere a light source
    const lx = cx + LIGHT[0] * R * 0.55;
    const ly = cy - LIGHT[1] * R * 0.55;
    const hl = g2.createRadialGradient(lx, ly, 0, lx, ly, R * 1.05);
    hl.addColorStop(0, `rgba(${GOLD_LIGHT.join(',')},0.22)`);
    hl.addColorStop(1, `rgba(${GOLD_LIGHT.join(',')},0)`);
    g2.fillStyle = hl;
    g2.beginPath();
    g2.arc(lx, ly, R * 1.05, 0, TAU);
    g2.fill();
  }

  function drawGlow() {
    if (!glowLayer) buildGlow();
    ctx.drawImage(glowLayer, 0, 0, W, H);
  }

  /* ── Faint lat/long wireframe — holds the silhouette ── */
  function drawWireframe(sinS, cosS) {
    const LAT = 9, LON = 13, SEG = 52;

    const stroke = (pts, alpha, lw) => {
      ctx.beginPath();
      ctx.moveTo(pts[0][0], pts[0][1]);
      for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i][0], pts[i][1]);
      ctx.strokeStyle = `rgba(${GOLD_LIGHT.join(',')},${alpha.toFixed(3)})`;
      ctx.lineWidth = lw;
      ctx.stroke();
    };

    for (let i = 1; i < LAT; i++) {
      const phi = (i / LAT) * Math.PI;
      const pts = [];
      let depth = 0;
      for (let j = 0; j <= SEG; j++) {
        const th = (j / SEG) * TAU;
        const [x, y, z] = rotate(
          Math.sin(phi) * Math.cos(th), Math.cos(phi), Math.sin(phi) * Math.sin(th),
          sinS, cosS,
        );
        pts.push([cx + x * R, cy - y * R]);
        depth += z;
      }
      depth /= SEG + 1;
      stroke(pts, 0.09 + 0.20 * ((depth + 1) / 2), 0.7);
    }

    for (let i = 0; i < LON; i++) {
      const th = (i / LON) * TAU;
      const pts = [];
      let depth = 0;
      for (let j = 0; j <= SEG; j++) {
        const phi = (j / SEG) * Math.PI;
        const [x, y, z] = rotate(
          Math.sin(phi) * Math.cos(th), Math.cos(phi), Math.sin(phi) * Math.sin(th),
          sinS, cosS,
        );
        pts.push([cx + x * R, cy - y * R]);
        depth += z;
      }
      depth /= SEG + 1;
      stroke(pts, 0.07 + 0.17 * ((depth + 1) / 2), 0.6);
    }

    // Silhouette edge, with a brighter arc on the lit side
    ctx.beginPath();
    ctx.arc(cx, cy, R, 0, TAU);
    ctx.strokeStyle = `rgba(${GOLD_LIGHT.join(',')},0.34)`;
    ctx.lineWidth = 1;
    ctx.stroke();

    const rim = Math.atan2(-LIGHT[1], LIGHT[0]);
    ctx.beginPath();
    ctx.arc(cx, cy, R, rim - 1.15, rim + 1.15);
    ctx.strokeStyle = `rgba(${GOLD_LIGHT.join(',')},0.55)`;
    ctx.lineWidth = 1.6;
    ctx.stroke();
  }

  /* ── Continent dots ──
     Bucketed by luminance so the whole field draws in ~7 fills
     instead of one per dot. */
  const BUCKETS = 7;

  function drawDots(sinS, cosS) {
    if (!points) return;
    const n = points.length / 3;
    const paths = [];
    for (let b = 0; b < BUCKETS; b++) paths.push([]);

    const baseR = Math.max(0.7, R * 0.0104);

    for (let i = 0; i < n; i++) {
      const [x, y, z] = rotate(points[i * 3], points[i * 3 + 1], points[i * 3 + 2], sinS, cosS);

      // Lambert-ish term against the light, then a hard falloff for the far side
      const lambert = x * LIGHT[0] + y * LIGHT[1] + z * LIGHT[2];
      // Generous ambient floor, modest directional term: with a strongly
      // directional light the globe's density tracks whichever hemisphere
      // happens to face the light, and the object pulses over a revolution.
      let lum = 0.46 + 0.54 * Math.max(0, lambert);
      // Behind the sphere: dim, but not absent — with a continuous
      // revolution, a Pacific-facing frame has very little land up front,
      // and killing the far side entirely makes the globe wash out for a
      // third of every turn.
      if (z < 0) lum *= 0.34 + 0.22 * (1 + z);
      lum *= sizeJitter[i * 2 + 1];
      if (lum < 0.04) continue;

      const b = Math.min(BUCKETS - 1, (lum * BUCKETS) | 0);
      // Thin the dots toward the silhouette, where the projection crowds them
      const r = baseR * (0.45 + 0.72 * ((z + 1) / 2)) * sizeJitter[i * 2];
      paths[b].push(cx + x * R, cy - y * R, r);
    }

    for (let b = 0; b < BUCKETS; b++) {
      const arr = paths[b];
      if (!arr.length) continue;
      const t = (b + 0.5) / BUCKETS;              // 0 → deep gold, 1 → light gold
      const cr = Math.round(GOLD_DEEP[0] + (GOLD_LIGHT[0] - GOLD_DEEP[0]) * t);
      const cg = Math.round(GOLD_DEEP[1] + (GOLD_LIGHT[1] - GOLD_DEEP[1]) * t);
      const cb = Math.round(GOLD_DEEP[2] + (GOLD_LIGHT[2] - GOLD_DEEP[2]) * t);
      ctx.fillStyle = `rgba(${cr},${cg},${cb},${(0.20 + 0.78 * t).toFixed(3)})`;
      ctx.beginPath();
      for (let i = 0; i < arr.length; i += 3) {
        const px = arr[i], py = arr[i + 1], pr = arr[i + 2];
        // Below ~1.3px a circle and a square are indistinguishable on screen,
        // and rects are markedly cheaper to path — which matters at ~10k dots
        if (pr < 0.65) {
          const d = pr * 2;
          ctx.rect(px - pr, py - pr, d, d);
        } else {
          ctx.moveTo(px + pr, py);
          ctx.arc(px, py, pr, 0, TAU);
        }
      }
      ctx.fill();
    }
  }

  /* ── Orbit rings ──
     Sampled in 3D, then drawn in two passes so they genuinely pass
     behind and in front of the sphere. Each is stroked twice: a wide
     soft pass and a narrow bright one, which reads like a lit tube. */
  function ringPoints(ring, phase) {
    const pts = [];
    const SEG = 130;
    // The azimuth sways within a bounded arc instead of revolving fully: a
    // free revolution takes every ring edge-on twice a cycle, where it
    // collapses to a line and the composition loses its orbits.
    const ang = ring.azi + Math.sin(phase * ring.speed) * RING_SWAY;
    const ci = Math.cos(ring.inc), si = Math.sin(ring.inc);
    const ca = Math.cos(ang);
    const sa = Math.sin(ang);

    for (let i = 0; i <= SEG; i++) {
      const t = (i / SEG) * TAU;
      // ellipse in its own plane
      let x = Math.cos(t) * R * ring.r;
      let y = Math.sin(t) * R * ring.r * ring.squash;
      let z = 0;

      // inclination (about X), then azimuth (about Y)
      const y1 = y * ci - z * si;
      const z1 = y * si + z * ci;
      const x2 = x * ca + z1 * sa;
      const z2 = -x * sa + z1 * ca;

      // share the globe's viewing tilt so they sit in the same space
      const cv = Math.cos(VIEW_TILT + pointer.y * 0.08);
      const sv = Math.sin(VIEW_TILT + pointer.y * 0.08);
      const y3 = y1 * cv - z2 * sv;
      const z3 = y1 * sv + z2 * cv;

      pts.push([cx + x2, cy - y3, z3]);
    }
    return pts;
  }

  function drawRingPass(pts, ring, front) {
    let run = [];
    const flush = () => {
      if (run.length < 2) { run = []; return; }
      for (const pass of [
        { w: ring.w * 4.0, a: ring.a * 0.13 },
        { w: ring.w * 1.4, a: ring.a * (front ? 1 : 0.34) },
      ]) {
        ctx.beginPath();
        ctx.moveTo(run[0][0], run[0][1]);
        for (let i = 1; i < run.length; i++) ctx.lineTo(run[i][0], run[i][1]);
        ctx.strokeStyle = `rgba(${GOLD_LIGHT.join(',')},${pass.a.toFixed(3)})`;
        ctx.lineWidth = pass.w;
        ctx.lineCap = 'round';
        ctx.stroke();
      }
      run = [];
    };

    for (const p of pts) {
      const isFront = p[2] >= 0;
      // A ring point in front of the sphere's silhouette but with z<0 is hidden
      if (isFront === front) run.push(p);
      else flush();
    }
    flush();
  }

  /* ── Glints travelling the rings ── */
  function drawGlints(phase, rings) {
    for (const g of GLINTS) {
      const pts = rings[g.ring].pts; // reuse this frame's curve — no recompute
      const t = ((g.t + phase * g.speed) % 1 + 1) % 1;
      const p = pts[Math.min(pts.length - 1, Math.floor(t * (pts.length - 1)))];
      if (!p) continue;

      // fade out while behind the sphere
      const behind = p[2] < 0 && Math.hypot(p[0] - cx, p[1] - cy) < R;
      const pulse = 0.55 + 0.45 * Math.sin(phase * 0.012 + g.t * 10);
      const alpha = (behind ? 0.10 : 0.85) * pulse;
      const rad = R * (behind ? 0.06 : 0.15);

      // Wide soft halo
      const halo = ctx.createRadialGradient(p[0], p[1], 0, p[0], p[1], rad);
      halo.addColorStop(0, `${GOLD_HALO}${(alpha * 0.34).toFixed(3)})`);
      halo.addColorStop(0.45, `${GOLD_HALO}${(alpha * 0.12).toFixed(3)})`);
      halo.addColorStop(1, `${GOLD_HALO}0)`);
      ctx.fillStyle = halo;
      ctx.beginPath();
      ctx.arc(p[0], p[1], rad, 0, TAU);
      ctx.fill();

      // Saturated gold flare — this is what actually reads against the cream
      const flare = ctx.createRadialGradient(p[0], p[1], 0, p[0], p[1], rad * 0.42);
      flare.addColorStop(0, `${GLINT_FLARE}${(alpha * 0.9).toFixed(3)})`);
      flare.addColorStop(0.5, `${GLINT_FLARE}${(alpha * 0.32).toFixed(3)})`);
      flare.addColorStop(1, `${GLINT_FLARE}0)`);
      ctx.fillStyle = flare;
      ctx.beginPath();
      ctx.arc(p[0], p[1], rad * 0.42, 0, TAU);
      ctx.fill();

      // Tight hot centre
      const core = ctx.createRadialGradient(p[0], p[1], 0, p[0], p[1], rad * 0.14);
      core.addColorStop(0, `${GLINT_HOT}${alpha.toFixed(3)})`);
      core.addColorStop(1, `${GLINT_HOT}0)`);
      ctx.fillStyle = core;
      ctx.beginPath();
      ctx.arc(p[0], p[1], rad * 0.14, 0, TAU);
      ctx.fill();
    }
  }

  /* ── One frame ── */
  function draw() {
    ctx.clearRect(0, 0, W, H);

    const sinS = Math.sin(spin);
    const cosS = Math.cos(spin);

    drawGlow();

    const rings = RINGS.map((r) => ({ ring: r, pts: ringPoints(r, ringPhase) }));
    for (const r of rings) drawRingPass(r.pts, r.ring, false); // behind

    drawWireframe(sinS, cosS);
    drawDots(sinS, cosS);

    for (const r of rings) drawRingPass(r.pts, r.ring, true);  // in front
    drawGlints(ringPhase, rings);
  }

  function tick() {
    pointer.x += (pointer.tx - pointer.x) * 0.045;
    pointer.y += (pointer.ty - pointer.y) * 0.045;
    spin += SPIN_SPEED;
    ringPhase += 1;
    draw();
    raf = requestAnimationFrame(tick);
  }

  function start() {
    if (raf || !ready || staticMode) return;
    raf = requestAnimationFrame(tick);
  }

  function stop() {
    if (raf) cancelAnimationFrame(raf);
    raf = null;
  }

  /* ── Pointer parallax (fine pointers only) ── */
  function bindPointer() {
    if (staticMode || window.matchMedia('(pointer: coarse)').matches) return;
    window.addEventListener('pointermove', (e) => {
      const rect = canvas.getBoundingClientRect();
      pointer.tx = ((e.clientX - (rect.left + rect.width / 2)) / window.innerWidth) * 2;
      pointer.ty = ((e.clientY - (rect.top + rect.height / 2)) / window.innerHeight) * 2;
    }, { passive: true });
  }

  /* ── Lifecycle ── */
  const io = new IntersectionObserver((entries) => {
    visible = entries[0].isIntersecting;
    if (visible) start(); else stop();
  }, { threshold: 0.02 });

  document.addEventListener('visibilitychange', () => {
    if (document.hidden) stop();
    else if (visible) start();
  });

  let resizeTimer = null;
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => {
      stop();
      if (resize() && ready) {
        if (staticMode) draw();
        else if (visible) start();
      }
    }, 150);
  });

  /* ── Boot ── */
  (async () => {
    if (!resize()) return;

    const land = await loadLandPoints(CANDIDATES);
    points = land && land.length ? land : null;

    if (points) {
      const n = points.length / 3;
      sizeJitter = new Float32Array(n * 2);
      for (let i = 0; i < n; i++) {
        sizeJitter[i * 2]     = 0.75 + Math.random() * 0.55; // size
        sizeJitter[i * 2 + 1] = 0.82 + Math.random() * 0.30; // opacity
      }
    }

    ready = true;
    bindPointer();
    draw();
    canvas.classList.add('is-ready');

    // Handle for driving frames without a live rAF (used when auditing the
    // composition in a headless/background tab). No cost when unused.
    canvas.__globe = { draw, step: (n = 1) => { spin += SPIN_SPEED * n; ringPhase += n; draw(); } };

    if (staticMode) return; // one frame is the whole show
    io.observe(canvas);
  })();
}
